# assets.py
"""
Définition des actifs financiers par catégories pour l'application Finance Viewer.
"""

# Définition des catégories d'actions par secteur
stock_categories = {
    "Tech": {
        "Apple": "AAPL",
        "Microsoft": "MSFT",
        "Google": "GOOGL",
        "Amazon": "AMZN",
        "Tesla": "TSLA",
        "Meta": "META",
        "NVIDIA": "NVDA",
        "Adobe": "ADBE",
        "Intel": "INTC",
        "IBM": "IBM",
        "Cisco": "CSCO",
        "Oracle": "ORCL",
        "Salesforce": "CRM",
        "AMD": "AMD",
        "PayPal": "PYPL",
        "Qualcomm": "QCOM",
        "Broadcom": "AVGO",
        "Texas Instruments": "TXN",
        "Applied Materials": "AMAT",
        "Micron Technology": "MU",
        "Autodesk": "ADSK",
        "Electronic Arts": "EA",
        "Activision Blizzard": "ATVI",
        "Uber": "UBER",
        "Lyft": "LYFT",
        "Palantir": "PLTR",
        "Snap": "SNAP",
        "Pinterest": "PINS",
        "Spotify": "SPOT",
        "Square/Block": "SQ",
        "Shopify": "SHOP",
        "Zoom": "ZM",
        "DocuSign": "DOCU",
        "Twilio": "TWLO",
        "Unity Software": "U",
        "Snowflake": "SNOW",
        "Cloudflare": "NET",
        "Dell Technologies": "DELL",
        "HP Inc.": "HPQ",
        "Lenovo": "LNVGY",
        "Sony": "SONY",
        "SAP": "SAP",
        "Accenture": "ACN",
        "Infosys": "INFY",
        "Cognizant": "CTSH",
    },
    "Banques & Finance": {
        "JPMorgan Chase": "JPM",
        "Bank of America": "BAC",
        "Wells Fargo": "WFC",
        "Goldman Sachs": "GS",
        "Morgan Stanley": "MS",
        "Visa": "V",
        "Mastercard": "MA",
        "American Express": "AXP",
        "BlackRock": "BLK",
        "Charles Schwab": "SCHW",
        "Citigroup": "C",
        "US Bancorp": "USB",
        "PNC Financial": "PNC",
        "Capital One": "COF",
        "BNY Mellon": "BK",
        "State Street": "STT",
        "Truist Financial": "TFC",
        "HSBC": "HSBC",
        "Barclays": "BCS",
        "UBS Group": "UBS",
        "Credit Suisse": "CS",
        "Deutsche Bank": "DB",
        "Santander": "SAN",
        "Lloyds Banking": "LYG",
        "Société Générale": "SCGLY",
        "BNP Paribas": "BNPQY",
        "Crédit Agricole": "CRARY",
        "ING Group": "ING",
        "Intesa Sanpaolo": "ISNPY",
        "Unicredit": "UNCRY",
        "Mitsubishi UFJ": "MUFG",
        "Sumitomo Mitsui": "SMFG",
        "ICBC": "IDCBY",
        "China Construction Bank": "CICHY",
        "Agricultural Bank of China": "ACGBY",
        "Royal Bank of Canada": "RY",
        "Toronto-Dominion Bank": "TD",
        "Bank of Montreal": "BMO",
        "Commonwealth Bank": "CMWAY",
        "ANZ": "ANZBY"
    },
    "Consommation": {
        "Walmart": "WMT",
        "Coca-Cola": "KO",
        "PepsiCo": "PEP",
        "McDonald's": "MCD",
        "Nike": "NKE",
        "Disney": "DIS",
        "Home Depot": "HD",
        "Starbucks": "SBUX",
        "Procter & Gamble": "PG",
        "Netflix": "NFLX",
        "Costco": "COST",
        "Target": "TGT",
        "Lowe's": "LOW",
        "TJX Companies": "TJX",
        "Colgate-Palmolive": "CL",
        "Kraft Heinz": "KHC",
        "General Mills": "GIS",
        "Kellogg's": "K",
        "Campbell Soup": "CPB",
        "Mondelez": "MDLZ",
        "Nestlé": "NSRGY",
        "Unilever": "UL",
        "Danone": "DANOY",
        "L'Oréal": "LRLCY",
        "Estée Lauder": "EL",
        "LVMH": "LVMUY",
        "Kering": "PPRUY",
        "Hermès": "HESAY",
        "Adidas": "ADDYY",
        "Puma": "PUMSY",
        "H&M": "HNNMY",
        "Inditex (Zara)": "IDEXY",
        "VF Corporation": "VFC",
        "Marriott International": "MAR",
        "Hilton": "HLT",
        "Booking Holdings": "BKNG",
        "Expedia": "EXPE",
        "Carnival Corporation": "CCL",
        "Royal Caribbean": "RCL",
        "Chipotle": "CMG",
        "Yum! Brands": "YUM",
        "Domino's Pizza": "DPZ",
        "Lululemon": "LULU",
        "Under Armour": "UAA",
        "Gap": "GPS"
    },
    "Santé & Pharmacie": {
        "Johnson & Johnson": "JNJ",
        "Pfizer": "PFE",
        "Merck": "MRK",
        "UnitedHealth": "UNH",
        "Abbott Labs": "ABT",
        "Eli Lilly": "LLY",
        "Amgen": "AMGN",
        "Bristol-Myers Squibb": "BMY",
        "AbbVie": "ABBV",
        "Gilead Sciences": "GILD",
        "Moderna": "MRNA",
        "Novo Nordisk": "NVO",
        "Novartis": "NVS",
        "Roche": "RHHBY",
        "Sanofi": "SNY",
        "AstraZeneca": "AZN",
        "GlaxoSmithKline": "GSK",
        "Bayer": "BAYRY",
        "Biogen": "BIIB",
        "Vertex Pharmaceuticals": "VRTX",
        "Regeneron": "REGN",
        "Illumina": "ILMN",
        "Baxter International": "BAX",
        "Medtronic": "MDT",
        "Boston Scientific": "BSX",
        "Stryker": "SYK",
        "Zimmer Biomet": "ZBH",
        "Danaher": "DHR",
        "Thermo Fisher Scientific": "TMO",
        "Edwards Lifesciences": "EW",
        "Intuitive Surgical": "ISRG",
        "CVS Health": "CVS",
        "Walgreens Boots Alliance": "WBA",
        "Cigna": "CI",
        "Anthem": "ANTM",
        "Humana": "HUM",
        "HCA Healthcare": "HCA",
        "Laboratory Corp. of America": "LH",
        "Quest Diagnostics": "DGX"
    },
    "Énergie": {
        "Exxon Mobil": "XOM",
        "Chevron": "CVX",
        "ConocoPhillips": "COP",
        "Shell": "SHEL",
        "BP": "BP",
        "TotalEnergies": "TTE",
        "Eni": "E",
        "Equinor": "EQNR",
        "Petrobras": "PBR",
        "PetroChina": "PTR",
        "Sinopec": "SNP",
        "Schlumberger": "SLB",
        "Halliburton": "HAL",
        "Baker Hughes": "BKR",
        "Phillips 66": "PSX",
        "Valero Energy": "VLO",
        "Marathon Petroleum": "MPC",
        "Occidental Petroleum": "OXY",
        "Devon Energy": "DVN",
        "EOG Resources": "EOG",
        "Pioneer Natural Resources": "PXD",
        "Kinder Morgan": "KMI",
        "Williams Companies": "WMB",
        "Enterprise Products Partners": "EPD",
        "Energy Transfer": "ET",
        "Enbridge": "ENB",
        "TC Energy": "TRP",
        "Cheniere Energy": "LNG",
        "EQT Corporation": "EQT",
        "NextEra Energy": "NEE",
        "Duke Energy": "DUK",
        "Southern Company": "SO",
        "Dominion Energy": "D",
        "Exelon": "EXC",
        "Iberdrola": "IBDRY",
        "Enel": "ENLAY",
        "Engie": "ENGIY",
        "EDF": "ECIFY"
    },
    "Automobile": {
        "Ford": "F",
        "General Motors": "GM",
        "Tesla": "TSLA",
        "Toyota": "TM",
        "Honda": "HMC",
        "Volkswagen": "VWAGY",
        "BMW": "BMWYY",
        "Mercedes-Benz": "MBGAF",
        "Stellantis": "STLA",
        "Ferrari": "RACE",
        "Porsche": "POAHY",
        "Hyundai": "HYMTF",
        "Kia": "KIMTF",
        "Suzuki": "SZKMY",
        "Nissan": "NSANY",
        "Subaru": "FUJHY",
        "Mazda": "MZDAY",
        "BYD": "BYDDY",
        "NIO": "NIO",
        "Li Auto": "LI",
        "XPeng": "XPEV",
        "Lucid Group": "LCID",
        "Rivian": "RIVN",
        "Fisker": "FSR",
        "Nikola": "NKLA",
        "Aptiv": "APTV",
        "Magna International": "MGA",
        "Lear Corporation": "LEA",
        "BorgWarner": "BWA",
        "Autoliv": "ALV",
        "Continental": "CTTAY",
        "Michelin": "MGDDY",
        "Bridgestone": "BRDCY",
        "Goodyear": "GT"
    },
    "Télécommunications": {
        "AT&T": "T",
        "Verizon": "VZ",
        "T-Mobile": "TMUS",
        "Comcast": "CMCSA",
        "Charter Communications": "CHTR",
        "Deutsche Telekom": "DTEGY",
        "Vodafone": "VOD",
        "Orange": "ORAN",
        "Telefonica": "TEF",
        "BT Group": "BT",
        "América Móvil": "AMX",
        "NTT": "NTTYY",
        "KDDI": "KDDIY",
        "SoftBank": "SFTBY",
        "China Mobile": "CHL",
        "China Telecom": "CHA",
        "Bharti Airtel": "BHARTIARTL.NS",
        "Reliance Jio": "RELIANCE.NS",
        "Rogers Communications": "RCI",
        "BCE Inc.": "BCE",
        "Telus": "TU",
        "Shaw Communications": "SJR",
        "Sprint": "S",
        "Dish Network": "DISH",
        "Liberty Global": "LBTYA",
        "Telecom Italia": "TI",
        "KPN": "KKPNY",
        "Telenor": "TELNY",
        "Telia": "TLSNY",
        "Swisscom": "SCMWY",
        "Proximus": "PROXF",
    },
    "Immobilier": {
        "American Tower": "AMT",
        "Prologis": "PLD",
        "Crown Castle": "CCI",
        "Simon Property Group": "SPG",
        "Equity Residential": "EQR",
        "Public Storage": "PSA",
        "Digital Realty Trust": "DLR",
        "Welltower": "WELL",
        "Boston Properties": "BXP",
        "Ventas": "VTR",
        "Essex Property Trust": "ESS",
        "AvalonBay Communities": "AVB",
        "Federal Realty": "FRT",
        "Vornado Realty Trust": "VNO",
        "SL Green Realty": "SLG",
        "Regency Centers": "REG",
        "Kimco Realty": "KIM",
        "Host Hotels & Resorts": "HST",
        "Realty Income": "O",
        "Iron Mountain": "IRM",
        "W. P. Carey": "WPC",
        "Unibail-Rodamco-Westfield": "URW",
        "Land Securities": "LDSCY",
        "British Land": "BTLCY",
        "Vonovia": "VONOY",
        "LEG Immobilien": "LEGIF",
        "Gecina": "GECFF",
        "Klepierre": "KLPEF",
        "Segro": "SEGXF",
        "Link REIT": "LKREF",
        "Sino Land": "SNLAY",
        "Sun Hung Kai Properties": "SUHJY",
        "Daiwa House Industry": "DWAHY",
        "Mitsui Fudosan": "MTSFY",
        "Mitsubishi Estate": "MITEY"
    },
    "Matériaux": {
        "BHP Group": "BHP",
        "Rio Tinto": "RIO",
        "Vale": "VALE",
        "Newmont": "NEM",
        "Barrick Gold": "GOLD",
        "Freeport-McMoRan": "FCX",
        "Southern Copper": "SCCO",
        "Anglo American": "NGLOY",
        "Glencore": "GLNCY",
        "ArcelorMittal": "MT",
        "Nucor": "NUE",
        "Steel Dynamics": "STLD",
        "United States Steel": "X",
        "POSCO": "PKX",
        "Nippon Steel": "NISTF",
        "JFE Holdings": "JFEEF",
        "Dow": "DOW",
        "DuPont": "DD",
        "Linde": "LIN",
        "Air Liquide": "AIQUY",
        "Air Products & Chemicals": "APD",
        "LyondellBasell": "LYB",
        "International Paper": "IP",
        "WestRock": "WRK",
        "Packaging Corp. of America": "PKG",
        "Amcor": "AMCR",
        "International Flavors & Fragrances": "IFF",
        "Eastman Chemical": "EMN",
        "Mosaic": "MOS",
        "CF Industries": "CF",
        "Nutrien": "NTR",
        "FMC Corporation": "FMC",
        "Albemarle": "ALB",
        "PPG Industries": "PPG",
        "Sherwin-Williams": "SHW",
        "Sika": "SIKA.SW",
        "Akzo Nobel": "AKZOY",
        "BASF": "BASFY"
    },
    "Aérospatiale & Défense": {
        "Boeing": "BA",
        "Lockheed Martin": "LMT",
        "Raytheon Technologies": "RTX",
        "Northrop Grumman": "NOC",
        "General Dynamics": "GD",
        "L3Harris Technologies": "LHX",
        "BAE Systems": "BAESY",
        "Airbus": "EADSY",
        "Safran": "SAFRY",
        "Rolls-Royce": "RYCEY",
        "Leonardo": "FINMY",
        "Thales": "THLLY",
        "Textron": "TXT",
        "CACI International": "CACI",
        "Spirit AeroSystems": "SPR",
        "TransDigm Group": "TDG",
        "Leidos": "LDOS",
        "HEICO": "HEI",
        "Curtiss-Wright": "CW",
        "Embraer": "ERJ",
        "Bombardier": "BDRBF",
        "Huntington Ingalls": "HII",
        "MTU Aero Engines": "MTUAY",
        "Rheinmetall": "RNMBY",
        "Korea Aerospace Industries": "047810.KS",
        "Mitsubishi Heavy Industries": "MHVYF",
        "Kawasaki Heavy Industries": "KWHIY",
        "IHI Corporation": "IHICF"
    },
    "Assurances": {
        "Berkshire Hathaway": "BRK-B",
        "Allianz": "ALIZY",
        "AIG": "AIG",
        "Chubb": "CB",
        "Progressive": "PGR",
        "Travelers": "TRV",
        "Allstate": "ALL",
        "MetLife": "MET",
        "Prudential Financial": "PRU",
        "AXA": "AXAHY",
        "Zurich Insurance": "ZURVY",
        "Swiss Re": "SSREY",
        "Munich Re": "MURGY",
        "Assicurazioni Generali": "ARZGY",
        "Prudential plc": "PUK",
        "Aviva": "AVVIY",
        "Legal & General": "LGGNY",
        "Aegon": "AEG",
        "NN Group": "NNGRY",
        "Tokio Marine": "TKOMY",
        "MS&AD Insurance": "MSADY",
        "Sompo": "SMPNY",
        "Ping An Insurance": "PNGAY",
        "China Life Insurance": "LFC",
        "Manulife Financial": "MFC",
        "Sun Life Financial": "SLF",
        "Great-West Lifeco": "GWLIF",
        "QBE Insurance": "QBIEY",
        "Insurance Australia": "IAUGY",
        "Suncorp Group": "SNMCY"
    }
}

# Dictionnaire plat des actions
stock_assets = {}
for category, assets in stock_categories.items():
    for name, ticker in assets.items():
        stock_assets[name] = ticker

# Listes des cryptomonnaies
crypto_assets = {
    "Bitcoin": "BTC-USD",
    "Ethereum": "ETH-USD",
    "Binance Coin": "BNB-USD",
    "Solana": "SOL-USD",
    "XRP": "XRP-USD",
    "Cardano": "ADA-USD",
    "Dogecoin": "DOGE-USD",
    "Polkadot": "DOT-USD",
    "Avalanche": "AVAX-USD",
    "Litecoin": "LTC-USD",
    "Polygon": "MATIC-USD",
    "Chainlink": "LINK-USD",
    "Stellar": "XLM-USD",
    "Uniswap": "UNI-USD",
    "Cosmos": "ATOM-USD",
    "Monero": "XMR-USD",
    "Algorand": "ALGO-USD",
    "VeChain": "VET-USD",
    "Filecoin": "FIL-USD",
    "Aave": "AAVE-USD",
    "Tezos": "XTZ-USD",
    "EOS": "EOS-USD",
    "The Graph": "GRT-USD",
    "Zcash": "ZEC-USD",
    "Decentraland": "MANA-USD",
    "Theta Network": "THETA-USD",
    "Axie Infinity": "AXS-USD",
    "Internet Computer": "ICP-USD",
    "Elrond": "EGLD-USD",
    "Fantom": "FTM-USD",
    "Shiba Inu": "SHIB-USD"
}

# Paires de devises étendues
currency_assets = {
    "EUR/USD": "EURUSD=X",
    "GBP/USD": "GBPUSD=X",
    "USD/JPY": "USDJPY=X",
    "USD/CAD": "USDCAD=X",
    "AUD/USD": "AUDUSD=X",
    "USD/CHF": "USDCHF=X",
    "NZD/USD": "NZDUSD=X",
    "EUR/GBP": "EURGBP=X",
    "EUR/JPY": "EURJPY=X",
    "EUR/CHF": "EURCHF=X",
    "GBP/JPY": "GBPJPY=X",
    "AUD/JPY": "AUDJPY=X",
    "AUD/NZD": "AUDNZD=X",
    "USD/HKD": "USDHKD=X",
    "USD/SGD": "USDSGD=X",
    "USD/CNY": "USDCNY=X",
    "USD/INR": "USDINR=X",
    "USD/MXN": "USDMXN=X",
    "USD/BRL": "USDBRL=X",
    "USD/ZAR": "USDZAR=X",
    "USD/RUB": "USDRUB=X",
    "USD/TRY": "USDTRY=X",
    "USD/PLN": "USDPLN=X",
    "USD/SEK": "USDSEK=X",
    "USD/NOK": "USDNOK=X",
    "USD/DKK": "USDDKK=X",
    "USD/HUF": "USDHUF=X",
    "USD/CZK": "USDCZK=X",
    "USD/ILS": "USDILS=X",
    "USD/THB": "USDTHB=X",
    "USD/IDR": "USDIDR=X",
    "USD/MYR": "USDMYR=X",
    "USD/PHP": "USDPHP=X",
    "EUR/AUD": "EURAUD=X",
    "EUR/CAD": "EURCAD=X",
    "EUR/NZD": "EURNZD=X",
    "GBP/AUD": "GBPAUD=X",
    "GBP/CAD": "GBPCAD=X",
    "GBP/NZD": "GBPNZD=X",
    "GBP/CHF": "GBPCHF=X"
}

# Ressources naturelles étendues
resource_assets = {
    "Or": "GC=F",
    "Argent": "SI=F",
    "Platine": "PL=F",
    "Palladium": "PA=F",
    "Cuivre": "HG=F",
    "Aluminium": "ALI=F",
    "Nickel": "LN=F",
    "Zinc": "LX=F",
    "Plomb": "LL=F",
    "Étain": "LT=F",
    "Pétrole brut WTI": "CL=F",
    "Pétrole brut Brent": "BZ=F",
    "Essence": "RB=F",
    "Fioul domestique": "HO=F",
    "Gaz naturel": "NG=F",
    "Blé": "ZW=F",
    "Maïs": "ZC=F",
    "Soja": "ZS=F",
    "Avoine": "ZO=F",
    "Riz": "ZR=F",
    "Coton": "CT=F",
    "Café": "KC=F",
    "Sucre": "SB=F",
    "Cacao": "CC=F",
    "Jus d'orange": "OJ=F",
    "Bétail vivant": "LE=F",
    "Bétail d'engraissement": "GF=F",
    "Porc maigre": "HE=F",
    "Bois de construction": "LBS=F",
    "Caoutchouc": "JRU=F"
}

# Indices organisés par pays/région
index_categories = {
    "États-Unis": {
        "S&P 500": "^GSPC",
        "Dow Jones Industrial Average": "^DJI",
        "NASDAQ Composite": "^IXIC",
        "Russell 2000": "^RUT",
        "S&P 100": "^OEX",
        "NASDAQ 100": "^NDX",
        "Dow Jones Transportation": "^DJT",
        "Dow Jones Utility": "^DJU",
        "NYSE Composite": "^NYA",
        "PHLX Semiconductor": "^SOX",
        "CBOE Volatility Index (VIX)": "^VIX",
        "S&P 400 Mid Cap": "^MID"
    },
    "Canada": {
        "S&P/TSX Composite": "^GSPTSE",
        "S&P/TSX 60": "^TSX",
        "S&P/TSX Venture Composite": "^JX"
    },
    "France": {
        "CAC 40": "^FCHI",
        "CAC Next 20": "CACNEXT20.PA",
        "CAC Mid 60": "CACMID60.PA",
        "CAC Small": "CACSMALL.PA",
        "SBF 120": "^SBF120"
    },
    "Allemagne": {
        "DAX": "^GDAXI",
        "MDAX": "^MDAXI",
        "SDAX": "^SDAXI",
        "TecDAX": "^TECDAX"
    },
    "Royaume-Uni": {
        "FTSE 100": "^FTSE",
        "FTSE 250": "^FTMC",
        "FTSE 350": "^FTLC",
        "FTSE All-Share": "^FTAS"
    },
    "Italie": {
        "FTSE MIB": "FTSEMIB.MI"
    },
    "Espagne": {
        "IBEX 35": "^IBEX"
    },
    "Pays-Bas": {
        "AEX": "^AEX"
    },
    "Belgique": {
        "BEL 20": "^BFX"
    },
    "Suisse": {
        "SMI": "^SSMI",
        "SPI": "^SPIX",
        "Swiss Leader Index": "^SLI"
    },
    "Scandinavie": {
        "OMX Stockholm 30": "^OMX",
        "OMX Copenhagen 20": "^OMXC20",
        "OMX Helsinki 25": "^OMXH25",
        "Oslo OBX": "^OSEOBX"
    },
    "Europe": {
        "EURO STOXX 50": "^STOXX50E",
        "STOXX Europe 600": "^STOXX",
        "FTSE Eurofirst 300": "^FTEU3"
    },
    "Japon": {
        "Nikkei 225": "^N225",
        "TOPIX": "^TOPX",
        "TOPIX Small": "^TSML",
        "JASDAQ": "^JSDA",
        "JPX-Nikkei 400": "^JPX400"
    },
    "Chine": {
        "Shanghai Composite": "^SSEC",
        "CSI 300": "^000300.SS",
        "FTSE China A50": "^FTFCNA50",
        "Shanghai Shenzhen CSI 300": "^CSI300",
        "Shenzhen Component": "^SZSC"
    },
    "Hong Kong": {
        "Hang Seng": "^HSI",
        "Hang Seng China Enterprise": "^HSCE"
    },
    "Corée du Sud": {
        "KOSPI": "^KS11",
        "KOSDAQ": "^KQ11"
    },
    "Taïwan": {
        "Taiwan Weighted": "^TWII"
    },
    "Singapour": {
        "Straits Times": "^STI"
    },
    "Australie": {
        "ASX 200": "^AXJO",
        "ASX 300": "^AXKO",
        "ASX 50": "^AFFL"
    },
    "Inde": {
        "NIFTY 50": "^NSEI",
        "BSE SENSEX": "^BSESN",
        "NIFTY Bank": "^NSEBANK",
        "NIFTY 500": "^CRSLDX"
    },
    "Brésil": {
        "Bovespa": "^BVSP"
    },
    "Mexique": {
        "IPC": "^MXX"
    },
    "Argentine": {
        "MERVAL": "^MERV"
    },
    "Afrique du Sud": {
        "JSE Top 40": "^JN0U.JO"
    },
    "Turquie": {
        "BIST 100": "^XU100"
    },
    "Russie": {
        "MOEX Russia": "IMOEX.ME",
        "RTS Index": "^RTSI"
    },
    "Moyen-Orient": {
        "Tel Aviv 35": "^TA35.TA",
        "Qatar Exchange": "^QSI",
        "Dubai Financial Market": "^DFMGI",
        "Abu Dhabi Securities Exchange": "^ADI",
        "Saudi Tadawul": "^TASI.SR"
    }
}

# Dictionnaire plat des indices
index_assets = {}
for country, indices in index_categories.items():
    for name, ticker in indices.items():
        index_assets[name] = ticker

